<a href="https://colab.research.google.com/github/Parishri07/Data-Science/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
##Python lists
y=[1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [ ]:
%timeit [j**4 for j in range(1,9)]

2.69 µs ± 57.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
%timeit np.arange(1,9)**4

2.47 µs ± 151 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [12]:
x = [10,20,30,40,50,60]
y = np.array(x)
y
print(y.ndim)
##ndim gives the dimension of the array

print(y.reshape(3,2))
## reshape(rows, cols)

1
[[10 20]
 [30 40]
 [50 60]]


In [ ]:
l = []
for i in range(1,5):
  int_1 = int(input("Enter: "))
  l.append(int_1)

print(np.array(l))

Enter: 12
Enter: 13
Enter: 14
Enter: 15
[12 13 14 15]


In [12]:
## 2-D array
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [10]:
## N dimensional array
arn = np.array([1,2,3,4], ndmin = 5)
print(arn)
print(arn.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


In [16]:
var = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var.reshape(2,3,2))
print()
print(var.reshape(-1))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
## Zeros
import numpy as np
ar_zero = np.zeros(4)
print(ar_zero)

print()

ar_zero1 = np.zeros((3,4))
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
## Ones
ar_one = np.ones((2,2))
print(ar_one)

[[1. 1.]
 [1. 1.]]


In [6]:
## Empty array
ar_em = np.empty(4)
print(ar_em)

[0.25 0.5  0.75 1.  ]


In [7]:
## Range array
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [8]:
## Diagonal elements as 1
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
## linspace
ar_lin = np.linspace(0,10,num=5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]


Random numbers

In [12]:
## rand()
## all values between 0 and 1

var = np.random.rand(4)
print(var)

print()

var1 = np.random.rand(2,5)
print(var1)

[0.12500396 0.1372585  0.1018629  0.8856601 ]
[[0.20171323 0.53528503 0.64475068 0.55627784 0.14388307]
 [0.73203534 0.49535386 0.77249714 0.89152139 0.84775006]]


In [13]:
## randn()
## numbers close to zero, positive or negative

var2 = np.random.randn(5)
print(var2)

[-0.02697582  0.77117809  0.45471307  2.30570719 -0.98640017]


In [14]:
## ranf()
## numbers in the interval [0.0,1.0)

var3 = np.random.ranf(4)
print(var3)

[0.60439799 0.10870924 0.68749449 0.93053052]


In [16]:
## randint(min, max, total_values)

var4 = np.random.randint(5,20,5)
print(var4)

[16 15  8 14 19]


Data types

In [18]:
arr = np.array([3,4,5,6])
print("Datatype: ", arr.dtype)
## dtype gives the datatype of elements in the variable

Datatype:  int64


In [20]:
var = np.array(["a", 2, 3.5])
print("Datatype: ",var.dtype)

Datatype:  <U32


In [4]:
x = np.array([1,2,3,4], dtype = np.int8)
print("Data type: ", x.dtype)

Data type:  int8


Arithmetic operation

In [13]:
var = np.array([1,2,3,4])
var1 = np.array([3,4,5,6])

varadd = var + 3
print(varadd)

varsum = var + var1
sumvar = np.add(var,var1)
print(varsum)
print(sumvar)

(4,)
[4 5 6 7]
[ 4  6  8 10]
[ 4  6  8 10]


Arithmetic Functions

In [9]:
var = np.array([2,3,4,5,1,6])

print(np.max(var))
print(np.min(var))
print(np.argmin(var)) ## gives index
print(np.sqrt(var))
print(np.sin(var))
print(np.cos(var))
print(np.cumsum(var))

6
1
4
[1.41421356 1.73205081 2.         2.23606798 1.         2.44948974]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427  0.84147098 -0.2794155 ]
[-0.41614684 -0.9899925  -0.65364362  0.28366219  0.54030231  0.96017029]
[ 2  5  9 14 15 21]


Broadcasting

performing arithmetic operations on array of different dimension, either dimension each comparison should be same or there must be atleast one 1

In [17]:
var1 = np.array([1,2,3])
var2 = np.array([[1],[2],[3]])
print(var1 + var2)
## 1x3 into 3x1, start from right corner, compare 1 with 3 then 3 with 1

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [4]:
var1 = np.array([[1],[2]])
var2 = np.array([[1,2,3],[3,4,5]])
print(var1)
print()
print(var2)
print()
print(var1 + var2)
## 2x1 into 2x3, start from right corner, compare 3 with 1 then 2 with 2
## final matrix is 2x3

[[1]
 [2]]

[[1 2 3]
 [3 4 5]]

[[2 3 4]
 [5 6 7]]


Indexing

In [5]:
var = np.array([9,8,7,6])
print(var[1])
print(var[-3])

8


In [8]:
var1 = np.array([[1,2,3,4],[4,5,6,7]])
print(var1)
print()
print(var1[0,1])

[[1 2 3 4]
 [4 5 6 7]]

2


Slicing

var[*start*: *stop*: *step*]

In [11]:
var = np.array([9,8,7,6,5,4,3,2,1])
print(var[1:5:2])
print(var[::3])

[8 6]
[9 6 3]


In [13]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr[1,1:])

[6 7 8]


Iteration

In [16]:
arr = np.array([[1,4],[5,8],[9,10]])

for i in np.nditer(arr):
  print(i)

## or can use 3 for loops

1
4
5
8
9
10


In [18]:
for i in np.nditer(arr,flags=['buffered'], op_dtypes="S"):
  print(i)

b'1'
b'4'
b'5'
b'8'
b'9'
b'10'


In [19]:
for i,d in np.ndenumerate(arr):
  print(i,d)

(0, 0) 1
(0, 1) 4
(1, 0) 5
(1, 1) 8
(2, 0) 9
(2, 1) 10


Copy vs View

In [25]:
var = np.array([1,2,3,4])
co = var.copy()
print("Copy: ",co)
## makes new array and copies the data

var[1]=7

vw = var.view()
print("View: ",vw)
## only views the original data

Copy:  [1 2 3 4]
View:  [1 7 3 4]


Join Array

In [35]:
var1 = np.array([[1,2],[3,4]])
var2 = np.array([[5,6],[7,8]])

new_arr1 = np.concatenate((var1, var2), axis=0)
print(new_arr1)
print()

new_arr2 = np.concatenate((var1, var2), axis=1)
print(new_arr2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]

[[1 2 5 6]
 [3 4 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [36]:
new_arr3 = np.stack((var1,var2), axis=1)
new1 = np.hstack((var1,var2))
new2 = np.vstack((var1,var2))
new3 = np.dstack((var1,var2))

print(new_arr3)
print()
print(new1)
print()
print(new2)
print()
print(new3)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]

[[1 2 5 6]
 [3 4 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


Split Array

In [38]:
var = np.array([[1,2],[3,4],[5,6]])

ar1 = np.array_split(var,3)
ar2 = np.array_split(var,3,axis=1)

print(var)
print()
print(ar1)
print()
print(ar2)

[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int64)]


Search

In [2]:
import numpy as np

var = np.array([2,4,5,6,8,2,9])
x = np.where( var == 2 )
print(x)

(array([0, 5]),)


In [6]:
var = np.array([1,2,3,3,4,5,6,8])
x = np.searchsorted(var,[7,8,9])
print(x)

y = np.searchsorted(var,7,side="right")
print(y)

[7 7 8]
7


Sort

In [9]:
var = np.array([2,4,5,8,6,2,9,1])
print(np.sort(var))

st = np.array(['a', 'f', 'd', 'b'])
print(np.sort(st))

[1 2 2 4 5 6 8 9]
['a' 'b' 'd' 'f']


Filter Array

In [10]:
st = np.array(['a', 'f', 'd', 'b'])

f = [True, False, False, True]

print(st[f])

['a' 'b']


In [14]:
var = np.array([1,2,3,3,4,5,5,6,8])
np.random.shuffle(var)
print(var)

[8 4 5 1 2 3 6 5 3]


In [15]:
x = np.unique(var, return_index = True, return_counts = True)
print(x)

(array([1, 2, 3, 4, 5, 6, 8]), array([3, 4, 5, 1, 2, 6, 0]), array([1, 1, 2, 1, 2, 1, 1]))


In [17]:
y = np.resize(var,(2,5))
print(y)

[[8 4 5 1 2]
 [3 6 5 3 8]]


In [20]:
print("Flatten: ",y.flatten(order='F'))
print()
print("Ravel: ",np.ravel(y,order='A'))

Flatten:  [8 3 4 6 5 5 1 3 2 8]

Ravel:  [8 4 5 1 2 3 6 5 3 8]


Insert

np.insert(*variable*, *position*, *data*)

In [31]:
var = np.array([1,2,3,4])
v = np.insert(var, (2,4), 4.9)
print(v)

x = np.append(var, 0)
print(x)

[1 2 4 3 4 4]
[1 2 3 4 0]


In [30]:
var1 = np.array([[1,2,3,4],[5,6,7,8]])
v = np.insert(var1, 2, [22,23,24,25], axis=0)
print(v)

print()

w = np.insert(var1, 2, [24,25], axis=1)
print(w)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [22 23 24 25]]

[[ 1  2 24  3  4]
 [ 5  6 25  7  8]]


Delete

In [34]:
var = np.array([1,2,3,4])
d = np.delete(var, 2)
print(d)

[1 2 4]


Matrix

In [35]:
var = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
var1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(var)
print()
print(var1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
var = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(var+var)
print()
print(var*var)
print()
print(var.dot(var))

print()

var1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(var1+var1)
print()
print(var1*var1)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [44]:
print(np.transpose(var))
## var.T
print()

print(np.swapaxes(var,0,1))

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [52]:
## print(np.linalg.inv(var))

print(np.linalg.matrix_power(var,2))
print()

print(np.linalg.matrix_power(var,0))
print()

## print(np.linalg.matrix_power(var,-2))

print(np.linalg.det(var))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]

0.0
