<a href="https://colab.research.google.com/github/Parishri07/Data-Science/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
##Python lists
y=[1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [6]:
%timeit [j**4 for j in range(1,9)]

2.69 µs ± 57.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [7]:
%timeit np.arange(1,9)**4

2.47 µs ± 151 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [13]:
x = [10,20,30,40]
y = np.array(x)
y
print(y.ndim)
##ndim gives the dimension of the array

1


In [12]:
l = []
for i in range(1,5):
  int_1 = int(input("Enter: "))
  l.append(int_1)

print(np.array(l))

Enter: 12
Enter: 13
Enter: 14
Enter: 15
[12 13 14 15]


In [14]:
## 2-D array
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [15]:
## N dimensional array
arn = np.array([1,2,3,4], ndmin = 5)
print(arn)

[[[[[1 2 3 4]]]]]
